user_pref("app.eula.accepted", true);
user_pref("calendar.agendaListbox.soondays", 28);
user_pref("calendar.integration.notify", false);
user_pref("calendar.item.editInTab", true);
user_pref("calendar.view.useSystemColors", true);
user_pref("calendar.view.visiblehours", 24);
user_pref("extensions.muttator.firsttime", false);
user_pref("general.autoScroll", true);
user_pref("general.warnOnAboutConfig", false);
user_pref("layers.acceleration.enabled", true);
// user_pref("mail.folderpane.showColumns", true);
user_pref("mail.incorporate.return_receipt", 1);
user_pref("mailnews.mark_message_read.delay", true);
// user_pref("mailnews.start_page.enabled", false);
user_pref("mail.pane_config.dynamic", 2);
user_pref("mail.receipt.request_return_receipt_on", true);
user_pref("mail.serverDefaultStoreContractID", "@mozilla.org/msgstore/maildirstore;1");
user_pref("mail.spam.logging.enabled", true);
user_pref("mail.spam.manualMark", true);
user_pref("mail.spam.markAsReadOnSpam", true);
user_pref("mail.SpellCheckBeforeSend", true);
user_pref("network.cookie.cookieBehavior", 2);
user_pref("network.http.altsvc.oe", true);
user_pref("network.http.upgrade-insecure-requests", true);
user_pref("places.history.enabled", false);
