#!/bin/sh

# This file runs when a DM logs you into a graphical session.
# If you use startx/xinit like a Chad, this file will also be sourced.

# This file's true location is in ~/.config/xprofile and a link exists to it in
# ~/.xprofile. If you do not use a DM, you may remove the link to it to have a
# cleaner home.

# Fix Gnome Apps Slow  Start due to failing services
# Add this when you include flatpak in your system
dbus-update-activation-environment --systemd DBUS_SESSION_BUS_ADDRESS DISPLAY XAUTHORITY

mpd &			# music player daemon-you might prefer it as a service though
remaps &		# run the remaps script, switching caps/esc and more; check it for more info
setbg &			# set the background with the `setbg` script
xrdb ${XDG_CONFIG_HOME:-$HOME/.config}/Xresources &	# use Xresources colors/settings on startup
xcompmgr &		# xcompmgr for transparency
dunst &			# dunst for notifications
xset r rate 300 50 &	# Speed xrate up
unclutter &		# Remove mouse when idle

# Initialize displays and wacom devices to sane (for me and my setup) defaults.
xrandr --output DP2 --pos 1366x0 --mode 1920x1080 --auto --scale 1.0x1.0 --output LVDS1 --pos 0x156 --auto --scale 1.0x1.0
xsetwacom set 16 MapToOutput LVDS1
xsetwacom set 17 MapToOutput LVDS1
xsetwacom set 23 MapToOutput LVDS1
setbg

redshift &		# adjusts the color temperature
fcitx &			# Input method
syncthing -no-browser	# peer-to-peer synchronization solution
ferdi &			# combine messaging services into one application
mailspring &		# mail client written in TypeScript with Electron/React

# ~/ Clean-up:
#rm .xsession-errors .xsession-errors.old

# program settings:
export QT_QPA_PLATFORMTHEME="gtk2"
